/* Slice the engine out of index.html and write it as an ES module so
   tests-rules.mjs can import it. Same arrangement as the Fatigue Assessor:
   the app stays one self-contained HTML file with no build step, and the
   tests read the real source rather than a copy that can drift away from it.

   model.gen.mjs is generated. Never commit it, never edit it. */
import fs from 'fs';

const src = fs.readFileSync(new URL('./index.html', import.meta.url), 'utf8');
const js = src.slice(src.indexOf('<script>') + 8, src.lastIndexOf('</script>'));

const START = 'const FAM_REV =';
const END   = '/* ── END OF ENGINE';
const a = js.indexOf(START), b = js.indexOf(END);
if (a < 0) throw new Error('marker miss: engine start (const FAM_REV)');
if (b < 0 || b < a) throw new Error('marker miss: engine end (END OF ENGINE)');

const engine = js.slice(a, b);

/* Anything the tests reach for. Adding a rule usually means adding its helper
   here too, or the test file cannot see it. */
const EXPORTS = [
  'FAM_REV','AIRPORTS','AP','UOA_LON_MIN','UOA_LON_MAX',
  'FDP_PLANNING','FDP_LIVE','FDP_AUGMENTED','FDP_OUTSIDE',
  'FDD_BASIC_MULTI','FDD_BASIC_SINGLE','FDD_AUG_TOTAL','FDD_AUG_CONT',
  'DP_MAX_HOURS','POST_BLOCKS_MIN','EXTRA_HOUR','NEAR_ABS_MINUTES','NEAR_PCT',
  'PATTERNS','TAXI_OUT_DEFAULT','TAXI_IN_DEFAULT',
  'parseDate','isoDate','addDays','dowIdx','fmtShort',
  'parseTime','fmtTime','fmtDur','fmtCount','utcOffset','absMin','localAt','resolveNear',
  'isUOA','nowAbs',
  'bandFor','pickBySectors','fdpLimit','fddLimit','against','blockOf',
  'computeDuty','latestPush',
];

fs.writeFileSync(new URL('./model.gen.mjs', import.meta.url),
  '/* GENERATED by tests-extract.mjs from index.html. Do not edit or commit. */\n'
  + engine + '\nexport {\n  ' + EXPORTS.join(', ') + '\n};\n');

console.log('extracted ' + engine.length + ' chars, ' + EXPORTS.length + ' exports');
